# minimal_main.py - Test version with database integration
from fastapi import FastAPI, Depends, HTTPException
from fastapi.middleware.cors import CORSMiddleware
import logging
from typing import List
from sqlalchemy.orm import Session
from sqlalchemy.exc import IntegrityError
from pydantic import BaseModel
from minimal_database import SessionLocal, Base  # Import the database setup
from minimal_models import Job, Detection  # Import your models

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Create FastAPI app
app = FastAPI(
    title="Mumbai Geo-AI Backend API",
    version="1.0.0",
    description="Geo-AI system for detecting new/illegal construction in Mumbai",
    docs_url="/docs",
    redoc_url="/redoc"
)

# Configure CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Temporary - open for testing
    allow_credentials=True,
    allow_methods=["GET", "POST", "PUT", "DELETE"],
    allow_headers=["*"],
)

# Dependency to get a database session
def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

# Pydantic model for request body validation
class JobCreate(BaseModel):
    name: str
    parameters: dict = {} # Optional parameters

# Pydantic model for response
class JobResponse(BaseModel):
    id: int
    name: str
    status: str
    # Add other fields as needed

# Simple test endpoints
@app.get("/")
async def root():
    """Root endpoint."""
    return {
        "message": "Mumbai Geo-AI Backend API",
        "version": "1.0.0",
        "status": "running",
        "docs": "/docs"
    }

@app.get("/health")
async def health():
    """Health check."""
    return {
        "status": "healthy",
        "service": "mumbai-geo-ai",
        "message": "Mumbai Geo-AI Backend is working correctly"
    }

@app.get("/test")
async def test():
    """Simple test endpoint."""
    return {
        "message": "Mumbai API test successful",
        "port": 8000,
        "conflict": "resolved"
    }

# --- NEW: Jobs Endpoints ---
@app.post("/jobs/", response_model=JobResponse, status_code=201)
async def create_job(job_data: JobCreate, db: Session = Depends(get_db)):
    """
    Create a new job in the database.
    """
    try:
        # Create a new Job instance
        db_job = Job(
            name=job_data.name,
            parameters=job_data.parameters,
            status="pending"
        )
        # Add to session
        db.add(db_job)
        # Commit the transaction
        db.commit()
        # Refresh the instance to get the ID generated by the database
        db.refresh(db_job)

        # Return the created job data
        return JobResponse(
            id=db_job.id,
            name=db_job.name,
            status=db_job.status
        )
    except IntegrityError as e:
        db.rollback()
        logger.error(f"Database integrity error creating job: {e}")
        raise HTTPException(status_code=400, detail="Job with this name already exists.")
    except Exception as e:
        db.rollback()
        logger.error(f"Error creating job: {e}")
        raise HTTPException(status_code=500, detail="Failed to create job.")

@app.get("/jobs/{job_id}")
async def get_job(job_id: int, db: Session = Depends(get_db)):
    """
    Get a specific job by ID.
    """
    job = db.query(Job).filter(Job.id == job_id).first()
    if not job:
        raise HTTPException(status_code=404, detail="Job not found")
    return job

@app.get("/jobs/")
async def list_jobs(skip: int = 0, limit: int = 10, db: Session = Depends(get_db)):
    """
    List all jobs.
    """
    jobs = db.query(Job).offset(skip).limit(limit).all()
    return jobs

if __name__ == "__main__":
    import uvicorn
    logger.info("Starting Mumbai Geo-AI Backend on port 8000...")
    uvicorn.run(
        "minimal_main:app",
        host="0.0.0.0", 
        port=8000,
        reload=True
    )